### ISSUE TITLE
Update documentation to explain how to get verbose output from guest log

### ISSUE THREAD

**Issue by ereshetova** [intel/ccc-linux-guest-hardening#105]
Documentation can have smth like:

1. change qemu_append line to select the one with more debug (it is commented out by default) in bkc/kafl/kafl_config.yaml

2. modify kafl.yaml in your local "data/test1/harness_name" to comment out "#log_crashes: True" and add
"log_hprintf: True" .

2. run with "fuzz.sh run build -p 2 --log-hprintf"

**Comment by ereshetova** [comment]
@tz0  could you please submit a PR to add a small section to https://github.com/intel/ccc-linux-guest-hardening#getting-started that is called smth like "Getting verbose output from the guest kernel". This is quite crucial for anyone who tries to debug anything with this setup.

**Comment by tz0** [comment]
Hi @ereshetova, please see PR[#112](https://github.com/intel/ccc-linux-guest-hardening/pull/112) for my draft.  I think it would be better to place the section in the getting_started tutorial but I can change that if you prefer the other way.

**Comment by ereshetova** [comment]
The PR is merged, thank you Tao!
