### ISSUE TITLE
initramfs unpacking failed: invalid magic at start of compressed image

### ISSUE THREAD

**Issue by williamcroberts** [intel/ccc-linux-guest-hardening#90]
initramfs unpacking failed: invalid magic at start of compressed image, see below image:

![PXL_20230221_170927088](https://user-images.githubusercontent.com/17750791/220463448-baed2c44-a6e2-4192-8886-65f38f69854b.jpg)

**Comment by williamcroberts** [comment]
I followed the steps on the README (https://github.com/intel/ccc-linux-guest-hardening#readme) and did a make deploy and the rebooted.

**Comment by Wenzel** [comment]
Hello @williamcroberts !
I fell like this is an issue related to an unsupported compression algorithm used by the initramfs.

**Comment by williamcroberts** [comment]
> Hello @williamcroberts ! I fell like this is an issue related to an unsupported compression algorithm used by the initramfs.

Why does `make deploy` pick a bad initramfs algorithm?

**Comment by williamcroberts** [comment]
Ok So it re-uses the existing initramfs, I thought it was generating a new one. So if the initramfs is ahead of the kernel, boom.

**Comment by il-steffen** [comment]
On debian/ubuntu the image is generated by `initramfs-tools` helpers. We don't do the full deploy with kernel install very often but it may be related to recent updates in Ubuntu or using a "too new" distro version.

You can change the default compression algo in `/etc/initramfs-tools/`

**Comment by williamcroberts** [comment]
So the workaround for others is to verify the compression algorithm in `/etc/initramfs-tools/initramfs.conf` (at least in ubuntu-22.04) and check the algorithm used for the COMPRESS variable. Mine was on zstd, changing it to lz4 and rebuilding the initramfs via `sudo update-initramfs -c -k all` and re-deploying.

**Comment by tz0** [comment]
I tried a fresh install using `make deploy` on a local machine and can boot into the SDV emulation kernel.
My compression is xz.

<img width="421" alt="image_2023-02-28_17-22-22" src="https://user-images.githubusercontent.com/30061838/221995667-22f2cf17-0a70-442d-b9bf-e942aeff3e82.png">

**Comment by williamcroberts** [comment]
Ok I was able to boot the environment, I did the following:
1. Did a fresh install of Ubuntu 22.04
2. Updated my init-ramfs compression algorithm from zstd to lz4
3. did the `make deploy`
4. rebooted

As a side note, many of the apps don't work as it complains about cgroup operation not being supported. Probably a mismatch between userspace and kernel version.

**Comment by williamcroberts** [comment]
Following the instructions here:
  - https://askubuntu.com/questions/1369947/after-ubuntu-21-10-upgrade-cannot-attach-cgroup-program-operation-not-permitt

and adding `systemd.unified_cgroup_hierarchy=0` to my kernel cmd line by following the instructions here:
  - https://wiki.ubuntu.com/Kernel/KernelBootParameters
worked and now browsers like Firefox launch.

**Comment by ereshetova** [comment]
I think we need a doc update to highlight this problem. I have run into the same on my machine.

**Comment by ereshetova** [comment]
So the steps to fix this (minimal set):

1. Edit /etc/initramfs-tools/initramfs.conf to change the algorithm from zstd to lz4
2. Rebuild the initramfs as 'sudo update-initramfs -c -k all'
3. Reboot

Nothing else is needed, you should be able to boot to the kafl kernel sucessfully. 

@tz0 could you please make a quick PR with the above instructions for workarounds to the docs? I have verified that the previous sequence works on my ubuntu 22 LTS

**Comment by williamcroberts** [comment]
The other thing is, where does this host kernel come from? Can we enable ztsd support in it?

**Comment by Wenzel** [comment]
@williamcroberts this host kernel comes from our [kafl.linux releases](https://github.com/IntelLabs/kafl.linux/releases/tag/sdv-nyx-5.6-rc1-v3)

`ZSTD` compression is only supported starting with kernels `5.8` or newer. (our latest SDV enabled kAFL kernel for TDX is `5.6`)

the mainline kAFL already supports kernel [5.10.73](https://github.com/IntelLabs/kafl.linux/releases/tag/gvtd-5.10.73), and will soon release a 6.0.0 kernel as well.

> Can we enable ztsd support in it?

It will be enabled by default, as long as you use a `5.8+` kernel

![image](https://user-images.githubusercontent.com/964610/223486420-cf9248cb-2c5c-4403-9301-bbc2cd0f2559.png)

We can of course document this.
And to fix this issue permanently, we have to upgrade our SDV enabled kernel to 5.10.73, or even 6.0.0
https://github.com/intel/ccc-linux-guest-hardening/blob/master/deploy/roles/bkc/meta/main.yml#L10

**Comment by il-steffen** [comment]
This is what Daniel + Pawan were working on, to lift the "SDV" host kernel to 6.x.

**Comment by tz0** [comment]
> So the steps to fix this (minimal set):
> 
> 1. Edit /etc/initramfs-tools/initramfs.conf to change the algorithm from zstd to lz4
> 2. Rebuild the initramfs as 'sudo update-initramfs -c -k all'
> 3. Reboot
> 
> Nothing else is needed, you should be able to boot to the kafl kernel sucessfully.
> 
> @tz0 could you please make a quick PR with the above instructions for workarounds to the docs? I have verified that the previous sequence works on my ubuntu 22 LTS

Yes.  Updated the README.md for the above.  [PR#94](https://github.com/intel/ccc-linux-guest-hardening/pull/94)

**Comment by ereshetova** [comment]
I merged the above PR. Now can close the issue.
